general:
  random_seed: 1669
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  batch_size: 5
  checkpoints_dir: checkpoints/
  colab:
    use_colab: 0
    best_chkp_name: best_chkp
    last_chkp_name: last_chkp

train:
  use_d_loss: 1
  save_chkp_n_epoches: 1
  crop_size: 256
  scheduler:
    D:
      start_lr: 1e-5
      end_lr: 1.5e-4
      step_size_up: 4000
    G:
      start_lr: 1e-3
      end_lr: 3e-4
      step_size_up: 4000
  optimizer:
    weight_decay: 5e-4
  logging:
    log_dir: tb_logger/
    log_io_n_batches: 10
    log_lr_n_batches: 50
    log_curr_loss_n_batches: 1
  epoches: 5000
  losses:
    lambda_gan_g: 0.15

test:
  resize_size: 256
  logging:
    log_curr_mets_n_batches: 1