general:
  random_seed: 1669
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  batch_size: 5
  checkpoints_dir: checkpoints/
  log_dir: tb_logger/
  colab:
    use_colab: 0
    best_chkp_name: best_chkp
    last_chkp_name: last_chkp

train:
  use_gan_loss: 1
  save_chkp_n_epoches: 1
  crop_size: 256
  D:
    update_n_batches: 1
    scheduler:
      start_lr: 1e-5
      end_lr: 1.5e-4
      step_size_up: 4000
  G:
    scheduler:
      start_lr: 1e-4
      end_lr: 3e-3
      step_size_up: 4000
  optimizer:
    weight_decay: 5e-4
  logging:
    log_io_n_batches: 10
    log_lr_n_batches: 50
    log_curr_loss_n_batches: 1
  epoches: 5000
  losses:
    lambda_gan_g: 0.15
    lambda_alpha_g: 1.0
    lambda_comp_g: 1.0
    lambda_lap_g: 1.0
  amp:
    use_amp: 1
    dtype: bf16
    use_grad_scaler: 0

test:
  crop_size: 256
  logging:
    log_curr_mets_n_batches: 1
    log_io_n_batches: 10